// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tasks.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countTasksByUserIdGroupedByStatus = `-- name: CountTasksByUserIdGroupedByStatus :many
SELECT status, COUNT(*) as count FROM tasks WHERE user_id = $1 GROUP BY status
`

type CountTasksByUserIdGroupedByStatusRow struct {
	Status TaskStatus `json:"status"`
	Count  int64      `json:"count"`
}

func (q *Queries) CountTasksByUserIdGroupedByStatus(ctx context.Context, userID uuid.UUID) ([]CountTasksByUserIdGroupedByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countTasksByUserIdGroupedByStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTasksByUserIdGroupedByStatusRow
	for rows.Next() {
		var i CountTasksByUserIdGroupedByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, status, priority, due_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, description, status, priority, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      TaskStatus     `json:"status"`
	Priority    TaskPriority   `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskById = `-- name: DeleteTaskById :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTaskById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTaskById, id)
	return err
}

const findAllTasksByUserId = `-- name: FindAllTasksByUserId :many
SELECT id, user_id, title, description, status, priority, due_date, created_at, updated_at FROM tasks WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) FindAllTasksByUserId(ctx context.Context, userID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, findAllTasksByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTasksByUserIdAndPriority = `-- name: FindAllTasksByUserIdAndPriority :many
SELECT id, user_id, title, description, status, priority, due_date, created_at, updated_at FROM tasks WHERE user_id = $1 AND priority = $2 ORDER BY created_at DESC
`

type FindAllTasksByUserIdAndPriorityParams struct {
	UserID   uuid.UUID    `json:"user_id"`
	Priority TaskPriority `json:"priority"`
}

func (q *Queries) FindAllTasksByUserIdAndPriority(ctx context.Context, arg FindAllTasksByUserIdAndPriorityParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, findAllTasksByUserIdAndPriority, arg.UserID, arg.Priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTasksByUserIdAndStatus = `-- name: FindAllTasksByUserIdAndStatus :many
SELECT id, user_id, title, description, status, priority, due_date, created_at, updated_at FROM tasks WHERE user_id = $1 AND status = $2 ORDER BY created_at DESC
`

type FindAllTasksByUserIdAndStatusParams struct {
	UserID uuid.UUID  `json:"user_id"`
	Status TaskStatus `json:"status"`
}

func (q *Queries) FindAllTasksByUserIdAndStatus(ctx context.Context, arg FindAllTasksByUserIdAndStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, findAllTasksByUserIdAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTaskById = `-- name: FindTaskById :one
SELECT id, user_id, title, description, status, priority, due_date, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) FindTaskById(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, findTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET title = $2, description = $3, status = $4, priority = $5, due_date = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, description, status, priority, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      TaskStatus     `json:"status"`
	Priority    TaskPriority   `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
