// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (keycloak_id)
VALUES ($1)
RETURNING id, keycloak_id
`

func (q *Queries) CreateUser(ctx context.Context, keycloakID string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, keycloakID)
	var i User
	err := row.Scan(&i.ID, &i.KeycloakID)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserById, id)
	return err
}

const findUserById = `-- name: FindUserById :one
SELECT id, keycloak_id FROM users WHERE id = $1
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserById, id)
	var i User
	err := row.Scan(&i.ID, &i.KeycloakID)
	return i, err
}
