-- +goose Up
ALTER TABLE users ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN email TEXT NOT NULL UNIQUE DEFAULT '';
ALTER TABLE users ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE users ALTER COLUMN name DROP DEFAULT;
ALTER TABLE users ALTER COLUMN email DROP DEFAULT;

-- +goose Down
ALTER TABLE users DROP COLUMN updated_at;
ALTER TABLE users DROP COLUMN created_at;
ALTER TABLE users DROP COLUMN email;
ALTER TABLE users DROP COLUMN name;
