version: "3"

vars:
  API_CMD: ./cmd

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  tools:
    desc: Install Go tools
    cmds:
      - go install tool

  dev:
    desc: Run Go API with live reload
    dotenv: ["../../.env"]
    cmds:
      - go tool air

  run:
    desc: Run Go API
    dotenv: ["../../.env"]
    cmds:
      - go run {{.API_CMD}}

  build:
    desc: Build Go API
    cmds:
      - go build {{.API_CMD}}

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run Go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy Go modules
    cmds:
      - go mod tidy

  migrate:up:
    desc: Run all pending migrations
    dotenv: ["../../.env"]
    cmds:
      - go tool goose -dir ./internal/db/postgresql/migrations postgres "$API_DB_URL" up

  migrate:down:
    desc: Rollback last migration
    dotenv: ["../../.env"]
    cmds:
      - go tool goose -dir ./internal/db/postgresql/migrations postgres "$API_DB_URL" down

  migrate:status:
    desc: Show migration status
    dotenv: ["../../.env"]
    cmds:
      - go tool goose -dir ./internal/db/postgresql/migrations postgres "$API_DB_URL" status

  migrate:create:
    desc: Create new migration
    cmds:
      - go tool goose -dir ./internal/db/postgresql/migrations -s create {{.CLI_ARGS}} sql

  sqlc:generate:
    desc: Generate Go code from SQL queries
    cmds:
      - go tool sqlc generate

  swagger:generate:
    desc: Generate Swagger docs
    cmds:
      - go tool swag init -g ./cmd/main.go -o ./docs
