definitions:
  health.HealthResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  description: REST API dla aplikacji todo
  title: Task API
  version: "1.0"
paths:
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthResponse'
      summary: Health check
      tags:
      - health
securityDefinitions:
  Keycloak:
    authorizationUrl: KEYCLOAK_AUTH_URL
    flow: accessCode
    tokenUrl: KEYCLOAK_TOKEN_URL
    type: oauth2
swagger: "2.0"
