definitions:
  health.HealthResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  title: Task API
  version: "1.0"
paths:
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthResponse'
      summary: Health check
      tags:
      - health
swagger: "2.0"
