#!/usr/bin/env bash
# Capture raw output from code metric tools into doc/generated/.
# Run via `task metrics` in the doc/ directory.

set -euo pipefail

DOC="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="$(cd "$DOC/.." && pwd)"
OUT="$DOC/generated"
API="$ROOT/apps/task-api"
FRONTEND="$ROOT/apps/task-frontend"

mkdir -p "$OUT"

# Lines of code via tokei (exclude generated files & lockfiles);
# transliterate fancy box-drawing chars to plain ASCII so the listing
# renders in LaTeX without a Unicode-aware monospace font.
tokei \
    --exclude '**/docs/docs.go' \
    --exclude '**/docs/swagger.*' \
    --exclude '**/generated/*' \
    --exclude '**/package-lock.json' \
    --exclude '**/*_test.go' \
    "$API" "$FRONTEND" \
    | sed -e 's/━/=/g' -e 's/─/-/g' -e 's/│/|/g' > "$OUT/tokei.txt"

# Cyclomatic complexity via gocyclo (top 15, excluding test files);
# strip absolute repo prefix so the listing stays compact.
gocyclo -top 15 -ignore '_test.go' "$API" \
    | sed "s|$ROOT/||g" > "$OUT/gocyclo.txt"

# Average cyclomatic complexity — extracted for use as \metricsAvgCC.
AVG=$(gocyclo -avg -ignore '_test.go' "$API" 2>&1 \
      | awk '/^Average:/ { print $2 }' \
      | tr '.' ',')
printf '%% Auto-generated by doc/scripts/gen-metrics.sh\n\\newcommand{\\metricsAvgCC}{%s}\n' "$AVG" \
    > "$OUT/avg_cc.tex"

echo "Average cyclomatic complexity: $AVG"
echo "Raw outputs written to $OUT"
